### ISSUE TITLE
how to use custom reducer with default flex store?

### ISSUE THREAD

**Issue by Stas-Buzunko** [ktalebian/flex-plugin-template-sample#5]
I need to use custom reducer for my custom view, cannot find a way to add it to existing store

**Comment by ktalebian** [comment]
@Stas-Buzunko take a look at https://github.com/twilio/flex-plugin-builder/blob/master/packages/create-flex-plugin/templates/js/src/DemoPlugin.js. If you plugin-builder v3, the sample plugin it generates for you, has a custom reducer.
